---
- name: installing consul
  include: manual_install.yml
  when: not use_hashicorp_repository

# - name: bootstrapping consul
#   include: consul_bootstrap.yml
#   when: consul_run_bootstrap

- name: Installing Consul via the HashiCorp repository
  include: repository_install.yml
  when: use_hashicorp_repository

- name: Laying out OS level configurations
  include: os_level_configuration.yml

# - name: Installing Consul via direct archive
#   include: manual_install.yml
#   when: not use_hashicorp_repository

- name: Laying out remaining items if not a packer image
  include: non_packer_install.yml
  when: not packer_build
