---
- name: Creating Consul group
  ansible.builtin.group:
    name: '{{ consul_group }}'
    system: true
  when: consul_create_account

- name: Creating Consul user
  ansible.builtin.user:
    name: '{{ consul_user }}'
    home: '{{ consul_home_directory }}'
    group: '{{ consul_group }}'
    shell: /sbin/nologin
    system: true
  when: consul_create_account

- name: Creating Consul directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: '0750'
  with_items:
    - '{{ consul_home_directory }}'
    - '{{ consul_data_directory }}'
    - '{{ consul_tls_directory }}'
    - '{{ consul_license_directory }}'
    - '{{ consul_data_directory }}/data'

- name: Creating Consul bin directory if outside of '/usr/bin'
  ansible.builtin.file:
    state: directory
    path: '{{ consul_install_directory }}'
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: '0750'
  when: consul_install_directory != "/usr/bin"

