---
- name: Restart Consul
  systemd:
    name: consul
    state: restarted
  when:
    - not packer_build

- name: Reload Consul daemon
  systemd:
    name: consul
    state: restarted
    daemon_reload: true
  when:
    - not packer_build
